-- Rename Datafiles

ALTER DATABASE RENAME FILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\SYSTEM.DBF'   TO 'C:\app\oracle\oradata\XE\SYSTEM.DBF';
ALTER DATABASE RENAME FILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\UNDOTBS1.DBF' TO 'C:\app\oracle\oradata\XE\UNDOTBS1.DBF';
ALTER DATABASE RENAME FILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\SYSAUX.DBF'   TO 'C:\app\oracle\oradata\XE\SYSAUX.DBF';
ALTER DATABASE RENAME FILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\USERS.DBF'    TO 'C:\app\oracle\oradata\XE\USERS.DBF';

-- Rename Temp file
ALTER DATABASE RENAME FILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\TEMP.DBF'     TO 'C:\app\oracle\oradata\XE\TEMP.DBF';



-- Rename Redo Log Files
ALTER DATABASE RENAME FILE 
    'C:\ORACLEXE\APP\ORACLE\FAST_RECOVERY_AREA\XE\ONLINELOG\O1_MF_2_7K7QDGXN_.LOG' TO
    'C:\app\oracle\fast_recovery_area\XE\ONLINELOG\O1_MF_2_7K7QDGXN_.LOG';

ALTER DATABASE RENAME FILE 
    'C:\ORACLEXE\APP\ORACLE\FAST_RECOVERY_AREA\XE\ONLINELOG\O1_MF_1_7K7QDCYN_.LOG' TO
    'C:\app\oracle\fast_recovery_area\XE\ONLINELOG\O1_MF_1_7K7QDCYN_.LOG';

